import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from "react";
import {useAtom} from "jotai";
import {encryptorAtom, signerAtom, signerPublicKeysAtom} from "@/state/crypto";
import {Dashboard} from "@/components/Dashboard";
import {axiosInstance} from "@/api/exios";
import {Configuration, PublicKeyPairApi} from "@/client_api";
import Container from "@/components/common/Container";

export default function Home() {
    const [_, setMyKeys] = useAtom(signerPublicKeysAtom)

    useEffect(() => {
        const getKeys = async () => {
            let response
            try {
                response = await new PublicKeyPairApi(new Configuration(), '', axiosInstance).apiPublicKeyPairGet()
            } catch {
                return;
            }
            const importedKeys: Record<number, CryptoKey> = {}
            for (const key of response.data) {
                const jsonKey: JsonWebKey = JSON.parse(key.publicVerifierKey!)
                importedKeys[key.id!] = await window.crypto.subtle.importKey("jwk", jsonKey, {
                    name: "ECDSA",
                    namedCurve: "P-384"
                }, true, ["verify"])
                setMyKeys({...importedKeys})
            }
        }
        getKeys()
    }, [setMyKeys])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Container>
                    <Dashboard/>
                </Container>
            </main>
        </>
    )

}
